# Generated by Django 5.0.4 on 2026-06-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_productionitem_diagnostics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizedcut',
            name='bar_length_mm',
            field=models.IntegerField(default=6000, help_text='Actual stock bar length this cut was placed on'),
        ),
        migrations.AlterField(
            model_name='optimizationrun',
            name='bar_length_mm',
            field=models.IntegerField(default=6000, help_text='Most common stock bar length used across this run. Individual profiles/cuts may use other available stock lengths; see OptimizationSegment and OptimizedCut for exact values.'),
        ),
        migrations.AlterField(
            model_name='optimizationsegment',
            name='bar_length_mm',
            field=models.IntegerField(default=6000, help_text='Most common stock bar length used in this segment. See individual OptimizedCut.bar_length_mm for exact per-bar lengths when multiple stock lengths were used.'),
        ),
    ]
