# Generated by Django 5.0.4 on 2026-06-20 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_systemprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileStockLength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length_mm', models.IntegerField(help_text='Stock bar length in mm')),
                ('cost_per_meter_override', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to use the profile’s standard cost per metre', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_lengths', to='catalog.profile')),
            ],
            options={
                'ordering': ['profile', 'length_mm'],
                'unique_together': {('profile', 'length_mm')},
            },
        ),
    ]
