# Generated by Django 5.0.4 on 2026-06-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_profilestocklength'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='material',
            field=models.CharField(choices=[('aluminium', 'Aluminium'), ('upvc', 'uPVC')], default='upvc', max_length=20),
        ),
    ]
